---
- name: Install required packages for database server
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
    - python3-venv
    - mariadb-server
  tags: db_packages
