---
- name: Deploy Flask App with Gunicorn and Nginx in Production
  hosts: db_and_web_servers
  become: yes
  become_method: sudo
  remote_user: adrian
  roles:
    - packages
    - mysql_db
    - flask_web
    - nginx
