---
- name: Deploy a mysql DB
  hosts: db_server
  become: yes
  become_method: sudo
  remote_user: adrian
  roles:
    - db_packages
    - mysql_db

- name: Deploy a Web Server
  hosts: web_server
  become: yes
  become_method: sudo
  remote_user: adrian
  roles:
    - web_packages
    - flask_web
    - nginx
