---
    - name: Ensure required packages are installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - python3-venv
        - mariadb-server
        - gunicorn
        - nginx
        - pkg-config
        - default-libmysqlclient-dev
      tags: packages          
