---
- name: Install required packages for web server
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
    - python3-venv
    - gunicorn
    - nginx
    - pkg-config
    - default-libmysqlclient-dev
  tags: web_packages
