    - name: Ensure MariaDB is running
      service:
        name: mariadb
        state: started
        enabled: true
      tags: mariadb

    - name: Create MySQL database
      command: >
        mysql -u root -e "CREATE DATABASE IF NOT EXISTS {{ db_name }};"
      become: yes
      become_user: root
      tags: mariadb

    - name: Create MySQL user and grant privileges
      command: >
        mysql -u root -e "CREATE USER IF NOT EXISTS '{{ db_user }}'@'%' IDENTIFIED BY '{{ db_password }}';
        GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'%';
        FLUSH PRIVILEGES;"
      become: yes
      become_user: root
      tags: mariadb

    - name: Create employees table in the database
      mysql_query:
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: localhost
        login_db: "{{ db_name }}"
        query: "CREATE TABLE IF NOT EXISTS employees (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), position VARCHAR(100), salary DECIMAL(10, 2));"
      tags: mariadb

    - name: Insert sample data into employees table
      mysql_query:
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: localhost
        login_db: "{{ db_name }}"
        query: "INSERT INTO employees (name, position, salary) VALUES ('John Doe', 'Engineer', 70000.00), ('Jane Smith', 'Manager', 90000.00);"
      tags: mariadb